service: test-backend-leve-saude

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-esbuild
  - serverless-offline
  
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: 'node20'
    platform: 'node'
    concurrency: 10
