service: test-backend-leve-saude

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  listSchedules:
    handler: src/agenda/controller/listSchedules.handler
    events:
      - http:
          path: agendas
          method: get

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    platform: node
